# Generated by Django 3.0.3 on 2020-04-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Raspberry',
        ),
    ]
