# Generated by Django 3.0.5 on 2020-05-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_raspberry_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='gateway',
            field=models.GenericIPAddressField(default=''),
        ),
    ]
