# Generated by Django 3.0.5 on 2020-05-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_raspberry_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberry',
            name='gateway',
            field=models.TextField(default=''),
        ),
    ]
