# Generated by Django 3.0.5 on 2020-05-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='snmp_vers',
            new_name='vers_snmp',
        ),
    ]
