# Generated by Django 3.0.3 on 2020-04-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('login_time', models.DateTimeField()),
                ('is_logged', models.BooleanField()),
            ],
        ),
    ]
