# Generated by Django 3.0.3 on 2020-04-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.BinaryField(),
        ),
    ]
