# Generated by Django 3.0.3 on 2020-04-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200418_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
