# Generated by Django 3.0.3 on 2020-04-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='id_key',
            new_name='identity_key',
        ),
    ]
