# Generated by Django 3.0.3 on 2020-04-21 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200420_1700'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
