# Generated by Django 3.0.3 on 2020-04-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
